# Generated by Django 4.1.3 on 2022-11-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_cont', models.CharField(max_length=100)),
                ('department_tel', models.CharField(max_length=3)),
                ('department_position', models.CharField(max_length=100)),
                ('position_first_name', models.CharField(max_length=100)),
                ('position_last_name', models.CharField(max_length=100)),
                ('position_patronymic', models.CharField(max_length=100)),
                ('position_mob_tel', models.CharField(max_length=35)),
                ('position_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
