# Generated by Django 4.1.3 on 2022-12-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_departures_alter_contacts_all_department_cont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts_all',
            old_name='department_cont',
            new_name='department_name',
        ),
    ]
