# Generated by Django 4.1.3 on 2022-12-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_department_cont_contacts_all_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts_all',
            name='department_name',
        ),
    ]
