# Generated by Django 4.1.4 on 2022-12-13 09:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tkp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.PositiveSmallIntegerField(default=2023, verbose_name='Номер ТКП')),
                ('data_tkp', models.DateField(default=datetime.date.today, verbose_name='Дата ТКП')),
                ('contragent', models.CharField(max_length=150, verbose_name='Организация (Клиент)')),
                ('offers_cost', models.PositiveSmallIntegerField(default=0, help_text='указывать сумму в рублях с НДС', verbose_name='Сумма ТКП')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('locality', models.CharField(max_length=150, verbose_name='Населенный пункт')),
                ('main_offer', models.TextField(verbose_name='Оборудование содержание, предложение')),
                ('tender', models.BooleanField(default=False, verbose_name='Тендер да/нет')),
                ('note', models.CharField(max_length=150, verbose_name='Примечание')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('url', models.SlugField(max_length=160)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tkp', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ТКП',
                'verbose_name_plural': 'Реестр ТКП',
            },
        ),
    ]
